### ISSUE TITLE
Turn on faster?

### ISSUE THREAD

**Issue by sstyle** [Kevin-De-Koninck/PleaseSleep#2]
Hi Kevin!
Is it possible to turn on wifi faster than 7sec after the lid open?

**Comment by Kevin-De-Koninck** [comment]
Hi,
yes you can do that. Just lower the number in this line: https://github.com/Kevin-De-Koninck/PleaseSleep/blob/master/PleaseSleep#L127

I’ve added this delay because I want to wait until the system is fully woken up from a hibernate sleep. If we don’t wait a couple of seconds, there’s a small chance that the system would freeze as soon as the script enables Airport again.

I think that 2 or 3 seconds should be sufficient but I can't guarantee this.

**Comment by sstyle** [comment]
Hi, Thanks! Awesome. There is no new method how to fix this issue with periodic wake up?

**Comment by Kevin-De-Koninck** [comment]
As far as I know Apple has not fixed the problem... This solution was the only one that worked for me
